package io.github.abhik9.expirywatch.core.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Material 3 "tonal spot" schemes generated from the brand seed color #3F7D3A (a fresh green),
// using the Material Color Utilities (2021 spec).

internal val LightColors = lightColorScheme(
    primary = Color(0xFF3D6838),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFBEF0B2),
    onPrimaryContainer = Color(0xFF265022),
    inversePrimary = Color(0xFFA3D398),
    secondary = Color(0xFF53634E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD6E8CE),
    onSecondaryContainer = Color(0xFF3C4B38),
    tertiary = Color(0xFF386569),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBCEBEF),
    onTertiaryContainer = Color(0xFF1E4D51),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFF7FBF1),
    onBackground = Color(0xFF191D17),
    surface = Color(0xFFF7FBF1),
    onSurface = Color(0xFF191D17),
    surfaceVariant = Color(0xFFDEE4D8),
    onSurfaceVariant = Color(0xFF42493F),
    surfaceTint = Color(0xFF3D6838),
    inverseSurface = Color(0xFF2D322B),
    inverseOnSurface = Color(0xFFEFF2E8),
    outline = Color(0xFF73796F),
    outlineVariant = Color(0xFFC2C8BC),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF7FBF1),
    surfaceDim = Color(0xFFD8DBD2),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF2F5EB),
    surfaceContainer = Color(0xFFECEFE6),
    surfaceContainerHigh = Color(0xFFE6E9E0),
    surfaceContainerHighest = Color(0xFFE0E4DA),
)

internal val DarkColors = darkColorScheme(
    primary = Color(0xFFA3D398),
    onPrimary = Color(0xFF0D380E),
    primaryContainer = Color(0xFF265022),
    onPrimaryContainer = Color(0xFFBEF0B2),
    inversePrimary = Color(0xFF3D6838),
    secondary = Color(0xFFBACCB3),
    onSecondary = Color(0xFF263422),
    secondaryContainer = Color(0xFF3C4B38),
    onSecondaryContainer = Color(0xFFD6E8CE),
    tertiary = Color(0xFFA0CFD3),
    onTertiary = Color(0xFF00363A),
    tertiaryContainer = Color(0xFF1E4D51),
    onTertiaryContainer = Color(0xFFBCEBEF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF10140F),
    onBackground = Color(0xFFE0E4DA),
    surface = Color(0xFF10140F),
    onSurface = Color(0xFFE0E4DA),
    surfaceVariant = Color(0xFF42493F),
    onSurfaceVariant = Color(0xFFC2C8BC),
    surfaceTint = Color(0xFFA3D398),
    inverseSurface = Color(0xFFE0E4DA),
    inverseOnSurface = Color(0xFF2D322B),
    outline = Color(0xFF8C9388),
    outlineVariant = Color(0xFF42493F),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF363A34),
    surfaceDim = Color(0xFF10140F),
    surfaceContainerLowest = Color(0xFF0B0F0A),
    surfaceContainerLow = Color(0xFF191D17),
    surfaceContainer = Color(0xFF1D211B),
    surfaceContainerHigh = Color(0xFF272B25),
    surfaceContainerHighest = Color(0xFF323630),
)
